apiVersion: v1
kind: Service
metadata:
  name: squidcode-backend-service
spec:
  type: ClusterIP
  selector:
    app: squidcode-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  resource:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
