apiVersion: v1
kind: Service
metadata:
  name: squidcode-frontend-service
spec:
  type: ClusterIP
  selector:
    app: squidcode-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
