apiVersion: apps/v1
kind: Deployment
metadata:
  name: squidcode-frontend
  namespace: squidcode
  labels:
    app: squidcode-frontend
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: squidcode-frontend
  template:
    metadata:
      labels:
        app: squidcode-frontend
    spec:
      containers:
        - name: squidcode-frontend
          image: ghcr.io/alemazzo/squid-code/frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "32Mi"
              cpu: "20m"
            limits:
              memory: "128Mi"
              cpu: "300m"
