apiVersion: apps/v1
kind: Deployment
metadata:
  name: squidcode-leetcode
  namespace: squidcode
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: squidcode-leetcode
  template:
    metadata:
      labels:
        app: squidcode-leetcode
    spec:
      containers:
        - name: squidcode-leetcode
          image: ghcr.io/alemazzo/squid-code/leetcode:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"
