name: squidcode-backend@deployment

on:
  workflow_run:
    workflows: ["squidcode-backend@release"]
    types:
      - completed

env:
  path: services/squidcode-backend/infrastructure/kubernetes

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: >-
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'main'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl replace --force -f $GITHUB_WORKSPACE/${{ env.path }}/ --recursive

      - name: Verify deployment
        run: kubectl rollout status deployment