name: backend
env:
  # Environment variables
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  # Commands
  build: ./gradlew build
  test: ./gradlew test
  deploy: ./gradlew dockerPushNative

on:
  push:
    paths:
      - squidcode-backend/**
  pull_request:
    paths:
      - squidcode-backend/**

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build
        working-directory: squidcode-backend
        run: '${{ env.build }}'

      - name: Test
        working-directory: squidcode-backend
        run: '${{ env.test }}'

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: >-
      success() &&
      github.event_name == 'push' && 
      github.ref == 'refs/heads/main'

    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate Dockerfile
        working-directory: squidcode-backend
        run: |
          ./gradlew dockerfileNative
          ./gradlew buildNativeLayersTask
          ./gradlew dockerPrepareContext

      - name: Build and Push Docker Image amd64
        uses: docker/build-push-action@v4
        with:
          context: ./squidcode-backend/build/docker/native-main
          file: ./squidcode-backend/build/docker/native-main/DockerfileNative
          platforms: linux/amd64
          push: true
          tags: alessandromazzoli/squidcode-backend:latest

      - name: Build and Push Docker Image arm64
        uses: docker/build-push-action@v4
        with:
          context: ./squidcode-backend/build/docker/native-main
          file: ./squidcode-backend/build/docker/native-main/DockerfileNative
          platforms: linux/arm64
          push: true
          tags: alessandromazzoli/squidcode-backend:latest