name: frontend-service

env:
  install: npm install
  build: npm run build
  applicationPath: services/frontend-service/application
  registry: registry.digitalocean.com
  image: alessandromazzoli/squidcode-frontend
  platforms: linux/amd64
  kubernetesPath: services/frontend-service/infrastructure/kubernetes

on:
  push:
    paths:
      - services/frontend-service/application/**
  pull_request:
    paths:
      - services/frontend-service/application/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      - name: setup-install
        working-directory: ${{ env.applicationPath }}
        run: |
          ${{ env.install }}
          
      - name: build
        working-directory: ${{ env.applicationPath }}
        run: |
          ${{ env.build }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: >-
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 18 

      - name: setup-install
        working-directory: ${{ env.applicationPath }}
        run: |
          ${{ env.install }}

      - name: setup-build
        working-directory: ${{ env.applicationPath }}
        run: |
          ${{ env.build }}

      - name: setup-qemu
        uses: docker/setup-qemu-action@v3
  
      - name: setup-buildx
        uses: docker/setup-buildx-action@v2

      - name: setup-doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: setup-doctl-registry
        run: doctl registry login --expiry-seconds 1200
      
      - name: build-and-push
        uses: docker/build-push-action@v4
        with:
          context: ${{ env.applicationPath }}
          file: ${{ env.applicationPath }}/Dockerfile
          platforms: ${{ env.platforms }}
          tags: ${{ env.registry }}/${{ env.image }}:latest
          push: true

  deploy:
    runs-on: ubuntu-latest
    needs: release
    if: >-
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main'
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup-doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: setup-kubeconfig
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

      - name: deploy
        run: kubectl replace --force -f $GITHUB_WORKSPACE/${{ env.kubernetesPath }}/ --recursive

      - name: verify
        run: kubectl rollout status deployment