name: infrastructure

env:
  path: infrastructure/kubernetes

on:
  push:
    paths:
      - infrastructure/kubernetes/**
    branches:
      - main

jobs:
  
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: setup-doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: setup-kubeconfig
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

      - name: deploy
        run: kubectl replace --force -f $GITHUB_WORKSPACE/${{ env.path }}/ --recursive

      - name: verify
        run: kubectl rollout status deployment