name: kubernetes

on:
  push:
    paths:
      - kubernetes/**
      - .github/workflows/kubernetes.yml
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl replace --force -f $GITHUB_WORKSPACE/kubernetes/ --recursive

      - name: Verify deployment
        run: kubectl rollout status deployment/ingress-nginx-controller -n ingress-nginx