name: leetcode

env:
  install: 'npm install'

on:
  push:
    paths:
      - 'squidcode-leetcode/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use a Node.js version supported by your Svelte app

      # Step 3: Install dependencies and build the app
      - name: Install dependencies and build
        working-directory: ./squidcode-frontend
        run: |
          ${{ env.install }}

  release:
    runs-on: ubuntu-latest
    needs: build
    if: >-
      success() &&
      github.event_name == 'push' && 
      github.ref == 'refs/heads/main'

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use a Node.js version supported by your Svelte app

      # Step 3: Install dependencies and build the app
      - name: Install dependencies and build
        working-directory: ./squidcode-frontend
        run: |
          ${{ env.install }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
  
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./squidcode-leetcode/
          file: ./squidcode-leetcode/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.REGISTRY_NAME }}/squidcode-leetcode:latest

  deploy:
    runs-on: ubuntu-latest
    needs: release
    if: >-
      success() &&
      github.event_name == 'push' && 
      github.ref == 'refs/heads/main'
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ secrets.CLUSTER_NAME }}

      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl replace --force -f $GITHUB_WORKSPACE/squidcode-leetcode/kubernetes/ --recursive

      - name: Verify deployment
        run: kubectl rollout status deployment/squidcode-leetcode