name: squidcode-leetcode@build

on:
  push:
    paths:
      - services/squidcode-leetcode/application/**
  pull_request:
    paths:
      - services/squidcode-leetcode/application/**

env:
  install: 'npm install'
  path: services/squidcode-leetcode/application
  image: alessandromazzoli/squidcode-leetcode
  platforms: linux/amd64

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  

      - name: Install dependencies and build
        working-directory: ${{ env.path }}
        run: |
          ${{ env.install }}